project:
  type: website
  output-dir: docs

website:
  title: "MACRO"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/

format:
  html:
    theme:
      - default
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-tools: false
    highlight-style: pygments
    html-math-method: katex
    page-layout: article
    reference-location: document
    callout-icon: false
    css: styles.css

jupyter: python3

