---
title: "理性预期和差分方程"
author: "Tu"
date: "2025-06-29"
categories: [macro]
---

当我们想要描述一个系统随时间的演化，微分方程和差分方程便自然地出现了。对于经典的物理系统而言，给定一组描述系统的方程和变量的初始值，该系统未来的动态便被唯一地确定了，这时我们说，这一系统是“决定论”的。

::: {.callout appearance="simple"}

“我们可以将宇宙的现状视为宇宙过去的影响，也是宇宙未来的起因。”

—— 拉普拉斯

:::

但在经济系统中，事情则变得有些微妙起来，考虑如下具有前瞻性预期（forward-looking expectation）的差分方程：
$$
y_t = a\mathbb{E}_t[ y_{t+1}] + bx_t
$$

上述方程形式常见于微观主体做最优化的一阶条件，它表明： $y_t$ 当期值不仅决定于某些外生的因素 $x_t$，还决定于对该变量未来值的预期 $\mathbb{E}_t[y_{t+1}]$。此时人的主观预期成为了一个系统状态重要的，甚至是决定性的因素！

当人们都预期一家银行经营良好时，银行便会正常运行。但若因为一些外部事件，甚至可能仅仅是谣言导致储户的预期发生了改变，认为这家银行有倒闭的风险，这时挤兑便发生了，最终这家银行仅仅是由于人们主观上的预期改变而真的倒闭，即使它的客观财务状况本身没有任何问题。

# 两类模型

我们首先区分两类带有主观预期的模型。出于简单考虑，我们先只考虑单变量、线性情形，后续推广到多变量情形是自然的。

## Type Ⅰ

考虑如下的差分方程：
$$
y_t = a\mathbb{E}_{t-1}^s[y_{t}] + bx_t
$$ {#eq-01}

其中 $y_t$ 是由该方程描述的内生变量，$x_t$ 是给定的外生随机变量，服从某个已知的概率生成过程。这里 $\mathbb{E}_{t-1}^s[y_{t}]$ 加上了上标 $s$，表示这里的期望是主观（subjective）的，它表示的是人对未来的模糊感受，用以区分基于客观概率计算的数学期望 $\mathbb{E}_{t-1}[y_{t}]$[^1-1]。有些拗口地说：过去对当前系统状态的预期塑造了当前系统的实际状态。

[^1-1]: 这一区分的作用将会在后文变得清晰。

::: {.callout-note appearance="default"}
## 例1 Muth的水果市场
考虑某种水果市场的局部均衡，假设消费者在$t$年对该水果的需求曲线如下：
$$
Q_{t}^{d} = -\beta P_t
$$ {#eq-02}
果农在上一年决定这种水果的播种面积，具体种植多少，则取决于果农对明年市场价格的主观预期，预期的价格越高，果农选择播种的面积也就越大，相应的这种水果在 $t$ 年的供给也就越多：
$$
Q_{t}^{s} = \gamma\mathbb{E}_{t-1}^s[P_{t}] + u_t
$$ {#eq-03}

在简单的线性供给曲线之上，我们增加了一个随机扰动 $u_t$  用来刻画影响实际产量的随机因素，包括天气、土壤肥力波动等。上述所有参数都为正，并且为了后续计算方便，相应的变量都用其对均衡的偏离量来表示，因此没有截距项[^1-2]。最后，由于水果显然不能存储到下一年，因此均衡时我们有：

[^1-2]: 考虑原始模型为 $Q_{t} = \alpha+ \beta P_t$ 包含截距项,均衡时有 $\bar{Q} = \alpha+ \beta \bar{P}$，两式相减即消去 $\alpha$，但相应的变量转变为对均衡量的偏离。

$$
Q_{t}^{d} = Q_{t}^{s}
$$ {#eq-04}

联立以上三式，我们就将 $t$ 期真实的价格 $P_t$ 表示为了主观预期 $\mathbb{E}_{t-1}^s[P_{t}]$ 的线性函数：
$$
P_{t} = -\frac{\gamma}{\beta}\mathbb{E}_{t-1}^s[P_{t}] - \frac{1}{\beta}u_t
$$ {#eq-05}

而这一形式正对应于[式(1)](#eq-01)。
:::

## Type Ⅱ

我们在宏观经济学中更常见到的方程具有如下形式：

$$
y_t = a\mathbb{E}_{t}^s[y_{t+1}] + bx_t
$$ {#eq-06}

这一方程与之前的方程非常相似，唯一的区别是预期向未来迭代了一期，但却给模型的求解带来了很大的不同。通常，我们称这一类型的方程是forward-looking的，这充分反应了人是具有主观能动性的，而不是像机械一样服从固定规则运行的。经济人总是在当下和未来之间权衡，而未来是不确定的，从而预期就变得尤为重要。

::: {.callout-note appearance="default"}
## 例2 风险中性定价
在风险中性的世界中，投资者只关心股票的预期收益，而不关心其风险，因此根据无套利原理，股票带来的预期收益应当等于无风险利率：
$$
\frac{\mathbb{E}_{t}^s[P_{t+1}] + d_t - P_t}{P_t} = r_f
$$ {#eq-07}

重新整理可得：
$$
P_t = \frac{1}{1+r_f} \mathbb{E}_{t}^s[P_{t+1}] + \frac{1}{1+r_f} d_t
$$ {#eq-08}

上式不过是在说当前的股票价格 $P_t$ 等于对下一期股票价格的预期 $\mathbb{E}_{t}^s[P_{t+1}]$ 加上股票分红 $d_t$ 后用无风险利率折现，而这一形式正对应于[式(6)](#eq-06)。
:::

# 预期的形成方式

当我们想要更进一步，或者说想要求解我们的模型时，遭遇了一个我们无法回避的问题，即人的预期是怎样形成的？当我们使用预期是主观的这样的词汇时，我们其实已经隐含了预期的任意性。观察现实世界我们的确发现不同的人对同一件事情的预期是五花八门的，人们可能仅对可重复的随机试验才能真正达成共识（例如掷骰子）。更致命的是，我们这里所讨论的是那些尚且能赋予概率的事件，即“已知的未知”，而事实上还存在无法被赋予概率的“真正的未知”。

一个有助于缓和情况的解释是，我们这里考虑的预期并不是个人的预期，而是对市场有决定力量的“市场预期”，即各种预期加总后平均意义下所表现出的一种预期模式。这里，我们回避了个体预期是如何加总的问题，而直接对市场预期进行建模。历史上，经济学家对预期的处理方式从一个极端到了另一个极端，而事实上，这两种处理方式在某种程度上也是最符合直觉的、形式上看起来比较简单的方式。

## 适应性预期

有时候我们会在市场上观察到一种现象，某一年的某种水果因为天气等原因导致产量较低，市场供不应求，价格上涨。这使得果农受到激励，扩大播种面积，导致第二年供过于求，价格下跌。经历了第二年的亏损，果农又减少了该品种的种植面积，这又导致第三年供不应求，如此循环往复，价格呈现出周期性的波动。

套用我们的例1，上面的故事不过是在说 $\mathbb{E}_{t-1}^s[y_{t}] = y_{t-1}$ ，即果农直接将当期的价格作为下一期价格的预期。稍作修改我们就得到了所谓的外推型预期（extrapolative expectation）：$\mathbb{E}_{t-1}^s[y_{t}] = y_{t-1} + \sigma(y_{t-1} - y_{t-2})$，即如果今年水果价格相对去年上涨，果农认为这种上涨趋势会在明年持续。但按照上述的逻辑，果农很快会发现自己的预期总是错误的，如果果农并没有那么“笨”，那么他应当会根据自己之前的错误来调整自己的预期，这便引出了适应性预期（adaptive expectation）的概念：
$$
\mathbb{E}_{t-1}^s[y_{t}] = \mathbb{E}_{t-2}^s[y_{t-1}] + \delta(y_{t-1} - \mathbb{E}_{t-2}^s[y_{t-1}])
$$ {#eq-09}

如果 $y_{t-1}$ 大于 $\mathbb{E}_{t-2}^s[y_{t-1}]$，说明过去的预期相对低估了，相应的明年的预期就应当上调，调整的强度取决于系数 $\delta$。

将[式(9)](#eq-09)适当重写得到
$$
\mathbb{E}_{t-1}^s[y_{t}] = \delta y_{t-1} + (1 - \delta)\mathbb{E}_{t-2}^s[y_{t-1}]
$$ {#eq-10}

进一步地，我们向后迭代，得到
$$
\begin{align}
\mathbb{E}_{t-1}^s[y_{t}] &= \delta y_{t-1} + (1 - \delta)(\delta y_{t-2} + (1-\delta)\mathbb{E}_{t-3}^s[y_{t-2}]) \\
&= \delta y_{t-1} + \delta(1-\delta) y_{t-2} + (1-\delta)^2 \mathbb{E}_{t-3}^s[y_{t-2}] \\
&\cdots \\
&= \delta(y_{t-1} + (1-\delta)y_{t-2} + (1-\delta)^2 y_{t-3} + \cdots)
\end{align}
$$ {#eq-11}

这里，我们假设了当 $n \to \infty$ 时，$\mathbb{E}_{t-n-1}^s[y_{t-n}]$ 是有限的。因此适应性预期等价于假设预期是过去所有历史值的加权平均。上述所有的预期形成方式可以总结为
$$


$$ {#eq-12}

## 理性预期



# 模型求解初步


# 当我们假设理性预期时，我们假设了什么