---
title: "Blanchard-Kahn Condition"
author: "Tu"
date: "2025-07-10"
categories: [macro]
---

当假设了理性预期后，求解带期望的线性差分方程转变为一个纯粹的数学问题，这里的复杂度在于我们求解的目标不再是一个数列，而是一个随机变量序列。因此，我们首先从一维情形出发，然后考虑二维情形，最后过渡到一般的多维情形。

# 一维情形

让我们从一个最 trivial 的没有不确定性的例子出发：

$$
y_{t+1} = \lambda y_{t}
$$ {#eq-01}

[(1)](#eq-01)就是一个标准的一维线性差分方程，那么什么叫做这样一个方程的解？Mathematically，我们就是要找到一个无穷序列 $\{y_t\}_{t=0}^{\infty}$ 使得它满足[(1)](#eq-01)。

显然，如果不给定额外的初始条件，有无穷多的 $\{y_t\}_{t=0}^{\infty}$ 都可以满足[(1)](#eq-01)，此时我们说无法确定一个唯一的解。只要任意给定一个初始条件，例如给定 $y_0 = \bar{y}$，那么通过后向迭代的方式，方程的解就唯一确定为 $y_t = {\lambda}^t \bar{y} \enspace \forall t \ge 0$。

我们还可以给定终点条件 $\lim_{t \to \infty } y_t < \infty$，此时我们能唯一确定一个解吗？答案取决于 $\lambda$ 的取值，如果 $\lambda \le 1$，那么从任何一个初始值 $y_0$ 出发，都有 $\lim_{t \to \infty } {\lambda}^t y_0 < \infty$，因此此时即使额外增加一个终点条件仍然不能确定一个唯一的解。当 $\lambda \gt 1$，由于此时给定的是终点条件，所以自然地我们需要前向迭代，令 $\phi = 1/\lambda$，将[(1)](#eq01)重写为：

$$
y_{t} = \phi y_{t+1}
$$ {#eq-02}

前向迭代，得到 $y_t = {\phi}^s y_{t+s}$，令 $s \to \infty$，由于此时 $\phi \lt 0$，应用我们的终点条件 $\lim_{t \to \infty } y_t < \infty$，得到 $y_t = 0 \enspace \forall t \ge 0$。因此当 $\lambda \gt 1$，终点条件也唯一确定了一个解，尽管这个解显得非常 trivial。特别的，这个终点条件反过来决定了我们的初始值 $y_0$ 必须等于0。

现在考虑存在不确定性的情形：

$$
\mathbb{E}_t[y_{t+1}] = \lambda y_{t}
$$ {#eq-03}

那么什么叫做一个带期望的线性差分方程的解？Mathematically，我们此时需要找的不再是一个实数序列，而是一个随机变量序列 $\{y_t\}_{t=0}^{\infty}$，同时回顾概率论的基本知识，随机变量实际上是定义在样本空间 $\Omega$ 的函数，因此我们真正的问题是：找到一个定义在样本空间 $\Omega$ 的函数序列 $\{y_t(\cdot)\}_{t=0}^{\infty}$ 满足[(3)](#eq03)

因此严格来说，我们还需要指定一个概率空间 $(\Omega, \mathbb{F}, P)$ 才能完整地描述上述的问题，但在我们目前线性的简单情形下，概率空间 $(\Omega, \mathbb{F}, P)$ 的具体性质并不影响我们求解。

对于[(3)](#eq03)，给定初始条件 $y_0 = \bar{y}$，能否确定一个唯一的解？答案是否定的，实际上我们可以有无穷多的随机变量序列满足条件：

- 假设现已找到一个解 $\{y_t\}_{t=0}^{\infty}$ 满足[(3)](#eq03)，且满足 $y_0 = \bar{y}$。

- 对所有 $t \ge 1$，令 $y'_{t} = y_{t} + \epsilon_t$，$y'_0 = y_0$。容易验证，$\{y'_t\}_{t=0}^{\infty}$ 也是一个解只要 $\mathbb{E}_t[\epsilon_{t+1}] = \lambda \epsilon_{t}$。

相反，此时如果给定终点条件 $\lim_{s \to \infty } \mathbb{E}_t[y_{t+s}] < \infty$，什么时候有唯一解？当 $\lambda \le 1$ 时，与我们给定初始条件的论证完全类似地，此时我们的解仍然是未定的。当 $\lambda \gt 1$，让我们类似地将[(3)](#eq03)重写为：

$$
y_{t} = \phi \mathbb{E}_t[y_{t+1}]
$$ {#eq-04}

前向迭代并应用迭条件期望定律，得到 $y_{t} = \phi^s \mathbb{E}_t[y_{t+s}]$，令 $s \to \infty$，得到 $y_t = 0 \enspace \forall t \ge 0$。需要注意的是，此时的 $y_t$ 并不是实数0，而是定义在样本空间 $\Omega$ 上的零函数。

宏观经济学通常会假设随机性来源于外生的随机过程，例如：

$$
y_{t} = \phi \mathbb{E}_t[y_{t+1}] + x_t
$$ {#eq-05}

$x_t$ 一般假设服从一个AR(1)过程：

$$
x_{t} = \rho x_{t-1} + u_{t}
$$ {#eq-06}

与之前的论证类似，此时方程存在唯一解的条件仍然是 $\phi < 1$（$\lambda > 1$），但知道了模型具有唯一解后，这个解应当具有什么样的形式？这里的关键在于，现在我们模型潜在的那个概率空间正是由我们外生的随机过程 $\{x_t\}_{t=0}^{\infty}$ 所定义，因此最终我们的解 $y_t$ 将会是 $x_t$ 的函数，又由于方程的线性性，最终解的形式一定是 $y_t = \alpha x_t$，这正是为什么我们可以应用“猜测法”的原因。

现在唯一的待定系数只剩下 $\alpha$，让我们将 $y_t = \alpha x_t$ 带入 [(5)](#eq05)：

$$
\begin{align*}
\alpha x_t &= \phi \mathbb{E}_t[\alpha (\rho x_t + u_{t+1})] + x_t \\
\alpha x_t &= \phi \alpha \rho x_t + x_t \\
\alpha x_t &= (1 + \phi \rho \alpha) x_t
\end{align*}
$$ {#eq-07}

由于上述等式需要对所有 $x_t$ 成立，因此有:

$$
 \alpha = 1 + \phi \rho \alpha
$$ {#eq-08}

解得 $\alpha = \frac{1}{1 - \phi \rho}$。

事实上，我们仍然可以使用之前的前向迭代法来验证我们的猜测法是否正确：



# 二维情形

# 一般情形